### ISSUE TITLE
on-missing flag to support disappearing metrics

### ISSUE THREAD

**Issue by chrisdarroch** [iangrunert/git-ratchet#10]
`git-ratchet` currently works by assuming metrics are only ever added, and never disappear.

The behaviour of `git-ratchet` when a metric disappears is to bail hard.

Tools such as ESLint -- which reports on the number of defects or errors -- will not report a metric when the count is zero.

This puts `git-ratchet` and `ESLint` (and tools like it) at odds: if you improve your code (i.e., you reduce your code's defects), the numbers go to zero, which causes them to stop being reported, which makes `git-ratchet` sad.

One possible solution would be to add an `--on-missing` flag to `git-ratchet`, whose options could be:
- error [default] : fail (return a non-zero exit code) when a metric is missing from the ratchet input
- set-zero: adjust the value of the metric to zero (0) and continue

Use of this flag would support ESLint's behaviour of only reporting stats with a non-zero error count. This is also beneficial for other tools who will not (or cannot) report rules that did not fail.

**Comment by iangrunert** [comment]
I've added a `--zero-on-missing` flag to `git-ratchet check` which should do what you want. This is released in v0.2.0, could you give it a spin and let me know if it works? I've only written a very basic test for it, so I'm not 100% confident it works currently.

**Comment by iangrunert** [comment]
Had some slight bugs that have been fixed in v0.2.1. Should be good to go now.
