### ISSUE TITLE
git-ratchet Not Building

### ISSUE THREAD

**Issue by TimAtLassian** [iangrunert/git-ratchet#2]
Howdy,

The `git-ratchet` installation using `go get` on our build agents is failing in CI. I am able to reproduce the failure locally, too:

```
▶ go get gopkg.in/iangrunert/git-ratchet.v0
# gopkg.in/iangrunert/git-ratchet.v0
../../go/src/gopkg.in/iangrunert/git-ratchet.v0/git-ratchet.go:27: not enough arguments in call to cmd.Check
▶ go version
go version go1.4.2 darwin/amd64
```

The latest v0 release was 20 days ago but the failure only started happening recently, so it be a problem with the way we're installing the package.

Any help or insights appreciated, thanks.

**Comment by iangrunert** [comment]
Hi Tim,

I've been doing some experimental work on the master branch which I think
might be causing your failure. There must be a failure case that isn't
getting picked up by CI.

I recommend using one of the official releases downloadable from github to
prevent this issue.

Cheers,

Ian.

**Comment by TimAtLassian** [comment]
Ok, we'll use the packages. Thanks for that Ian :+1:
