### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by loeschg** [iangrunert/git-ratchet#9]
Just exploring this project, and I'm having trouble getting started.

I've downloaded the binary, made it executable, and when I run `git ratchet check -w` and enter values, nothing seems to happen. 

```
> git ratchet check -w
  test,100
```

Am I misunderstanding instructions?

**Comment by chrisdarroch** [comment]
When you feed measures in to `git-ratchet` via stdin in a terminal window, you'll need to send `^D` to signify the end of input. [Read this StackOverflow answer for a longer explanation](http://unix.stackexchange.com/questions/16333/how-to-signal-the-end-of-stdin-input-in-bash)

It may be easier to start testing by putting your measures in a file, then feeding that in to `git-ratchet`.

```
touch measures.csv
echo "test,100" > measures.csv
git ratchet check -v -w < measures.csv
```

**Comment by loeschg** [comment]
Did the trick. Thanks!
